name: Generaye Javadoc

on:
  push:
    branches:
      - main

jobs:
  javadoc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'

      - name: Generate Javadoc
        run: |
          javadoc -d docs -sourcepath src -subpackages .
      
      - name: Upload Javadoc Documentation
        uses: actions/upload-artifact@v4
        with:
          name: javadoc
          path: docs